name: cbnew-auto-push

on:
  schedule:
    # 每工作日9:00执行，转为UTC要减8小时
    - cron: '0 1 * * 1-5'
  workflow_dispatch: # 这一行将允许您手动启动此工作流

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v2
      with:
          ref: master

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: '^1.17' # or any other version you'd like

    - name: Run cbnew.go
      run: go run cbnew.go -barkkey=${{ secrets.BARK_KEY }}
