name: cbnew-auto-push

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch: # 手动触发
  schedule: # 计划任务触发
    - cron: '0 1 * * 1-5'

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Check out code
      uses: actions/checkout@v2-beta
      with:
          ref: master

    - name: Run cbnew push job
      run: |
        cd bin
        chmod 773 cbnew
        ./cbnew -barkkey=${{ secrets.BARK_KEY }}
